server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appbase
    username: user1
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


